Make contract return nullish values without explicit mocking (#17)
As the added unit test demonstrates, we are at the moment not able to invoke a method on the mocked contract from another smart contract (ContractUnderTest) without previously setting an expectation via e.g. `givenAnyReturnBool(false)`.

Since fallbackExpectation was set to empty, we would run into the following error:

```
Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

This PR makes it that our fallback value is not empty but instead the abi encoding of false (`0x0000000000000000000000000000000000000000000000000000000000000000`).

This way we won't need to call

```
await mock.givenAnyReturn(false)
```

but instead can use the mock right after initialization and get nullish values.

### Test Plan

Added unit test.